In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn

In [22]:
data = pd.read_csv("./HDB.csv")

In [23]:
data.head()

         Date       Open       High        Low      Close  Adj Close   Volume
0  2016-11-17  33.005001  33.005001  32.334999  32.424999  31.726246  2446400
1  2016-11-18  32.584999  32.584999  31.870001  32.285000  31.589264  2107800
2  2016-11-21  31.990000  32.119999  31.160000  31.250000  30.576569  3148000
3  2016-11-22  31.570000  31.684999  31.155001  31.325001  30.649952  1890000
4  2016-11-23  31.180000  31.535000  31.105000  31.430000  30.752689  1878000

In [24]:
data.drop("Date", inplace = True, axis = 1)

In [25]:
data.describe()['Open']

count    1258.000000
mean       54.389348
std        12.490894
min        29.700001
25%        47.000000
50%        50.877500
75%        62.687501
max        84.699997
Name: Open, dtype: float64

In [26]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [27]:
def scale_data(data):
    
    train_data = data[:int(0.8 * len(data))]
    test_data = data[int(0.8 * len(data)):]
    
    scaler = MinMaxScaler()
    
    for column in train_data.columns:
        
        values = train_data[column]
        values = np.array(values)
        values = values.reshape(-1, 1)
        train_data[column] = scaler.fit_transform(values)
        train_data[column] = train_data[column].apply(lambda X: round(X, 4))
        
        values = test_data[column]
        values = np.array(values)
        values = values.reshape(-1, 1)
        test_data[column] = scaler.fit_transform(values)
        test_data[column] = test_data[column].apply(lambda X: round(X, 4))
        
        
        
    return train_data, test_data

In [28]:
train_data, test_data = scale_data(data)

/tmp/ipykernel_86373/1572262777.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = train_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = test_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = train_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = test_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = train_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = test_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = train_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = test_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = train_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = test_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[column] = train_data[column].apply(lambda X: round(X, 4))
/tmp/ipykernel_86373/1572262777.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = scaler.fit_transform(values)
/tmp/ipykernel_86373/1572262777.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[column] = test_data[column].apply(lambda X: round(X, 4))

In [29]:
train_data.head()

     Open    High     Low   Close  Adj Close  Volume
0  0.0840  0.0780  0.0727  0.0725     0.0702  0.2140
1  0.0733  0.0673  0.0608  0.0689     0.0667  0.1791
2  0.0582  0.0555  0.0426  0.0424     0.0411  0.2863
3  0.0475  0.0444  0.0424  0.0443     0.0429  0.1566
4  0.0376  0.0406  0.0411  0.0470     0.0455  0.1554

In [30]:
test_data.head()

        Open    High     Low   Close  Adj Close  Volume
1006  0.1313  0.1468  0.1478  0.1264     0.1264  0.1984
1007  0.1500  0.1417  0.0693  0.0383     0.0383  0.3754
1008  0.0066  0.0000  0.0233  0.0070     0.0070  0.2265
1009  0.0353  0.0297  0.0198  0.0000     0.0000  0.2283
1010  0.0331  0.0275  0.0250  0.0064     0.0064  0.1195

In [31]:
preprocessed = pd.concat([train_data, test_data], axis = 0)

In [32]:
preprocessed.loc[preprocessed["Close"] == 0, "Close"] = 0.0001

In [33]:
preprocessed.to_csv("process.csv", index=False)

In [34]:
df = pd.read_csv("./process.csv")

In [35]:
df

        Open    High     Low   Close  Adj Close  Volume
0     0.0840  0.0780  0.0727  0.0725     0.0702  0.2140
1     0.0733  0.0673  0.0608  0.0689     0.0667  0.1791
2     0.0582  0.0555  0.0426  0.0424     0.0411  0.2863
3     0.0475  0.0444  0.0424  0.0443     0.0429  0.1566
4     0.0376  0.0406  0.0411  0.0470     0.0455  0.1554
...      ...     ...     ...     ...        ...     ...
1253  0.2791  0.2717  0.3056  0.2852     0.2998  0.2097
1254  0.2686  0.2672  0.3033  0.2812     0.2957  0.1106
1255  0.2587  0.3048  0.3068  0.3043     0.3190  0.1555
1256  0.2907  0.3076  0.2974  0.2597     0.2742  0.0767
1257  0.2488  0.2370  0.2421  0.2255     0.2399  0.2231

[1258 rows x 6 columns]

In [36]:
df[df["Close"] == 0]

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []